//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevCodePeople
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string codeName { get; set; }
        public int person_id { get; set; }
    }
}
